### ISSUE TITLE
List of scenarios to load?

### ISSUE THREAD

**Issue by holm76** [AluminumAngel/gloom#11]
Is there a way to store different scenarios and save them for others?

Would be nice to have a growing library of existing scenarios to pick from with all walls and traps and obstacles already build so you would only need to place monsters and characters to make the given situation.

**Comment by holm76** [comment]
Just found the scenario list on Reddit. Cool

https://www.reddit.com/r/Gloomhaven/comments/anaevw/monster_mover_scenarios/

**Comment by AluminumAngel** [comment]
As you've found, you can save and share scenarios by clicking the Share Scenario button.

I'll maintain back compatibility with old URLs through future updates.
