### ISSUE TITLE
Icy terrain and allies

### ISSUE THREAD

**Issue by rmsgrey** [AluminumAngel/gloom#23]
Scenario: a monster with Move 1 at one end of a line of icy terrain with a character at the other and another monster on an intervening (icy) hex.
Current behaviour: the monster moves the full length of the ice slide and attacks the character
Expected behaviour: the monster's slide is blocked by the other monster (also a figure) and it only moves to stand adjacent to its ally on the slide.

There are also (presumably related) issues when the second monster is on the hex after the slide, when the active monster will not use the icy terrain at all.

**Comment by AluminumAngel** [comment]
You are correct. I did not account for figures stopping an icy terrain slide. In fact, I think I missed reading that detail in the rules entirely. I will fix this.

**Comment by AluminumAngel** [comment]
Some scenarios demonstrating the issue:

https://gloom.aluminumangel.org/UQgEBBvAgNjAEANjBkYMbJiBEQMUAA
https://gloom.aluminumangel.org/UQgEBBvggNjAEANjBkYMjBkYMYChDCgA
https://gloom.aluminumangel.org/UQQEBBvggNjAEANjBkYMjBkYMYChDCgA

**Comment by AluminumAngel** [comment]
In other news, the URL of any scenario with an icy terrain hex (as per those in above comment) is broken.

**Comment by AluminumAngel** [comment]
Problem wasn't in the URLs. It was in the parsing of them.

Fixed in v2.11.1.

**Comment by Toucan4Life** [comment]
Hi @AluminumAngel, could you upload the updated code to github if it's possible please? I would like the check the change of the latests version if you don't mind :) Thanks for all you hard work by the way

**Comment by AluminumAngel** [comment]
Yes, I will do so as part of this fix. I've done a poor job of keeping GitHub up to date with my local version control.

**Comment by AluminumAngel** [comment]
This issue is resolved in v2.11.2, now live.

**Comment by AluminumAngel** [comment]
@Toucan4Life, I've uploaded the latest code.
