### ISSUE TITLE
Grid is too small for some scenarios

### ISSUE THREAD

**Issue by Serneum** [AluminumAngel/gloom#4]
I've been [building out some scenarios](https://boardgamegeek.com/article/31661482#31661482) for my group so we can load them up quickly, if needed.

- [Scenario 52](https://gloom.aluminumangel.org/AQQEMAf2rCFAgAABQgMCBAgQIECgkICwgABhAUHCAoKFBgQJDQgWHhAgWLAgwQIECRAgWIBgQYIFCAoWECRQgGABAgMKECBQgACBAgQJEBxQmECAIAEBAgQIEECQAKECgYEFCBIgWIAAAQIECAwoQLBgIYJAAgQLEwgQIEhIQKhAgPCA0IAAAQIECQ0IEQgWFhAgRCBYgAABAgQIDwgWPhAojCBAgAA) is the largest scenario to have hit my table so far and the grid is just 3-4 rows too small to complete it.
- [Scenario 15](https://gloom.aluminumangel.org/AQgEMAfKPCBAgAABAoQNhAWEDoQEhA0EBAgUIIDQgZCAsIGgAAECCR0ICQgbCAsIHQgQKEDoQLDwgZCA8IAAgQIECAsIECBQgCBBAgQIFQgQIEigkIBgIQGBAoQGBAgUIDQgQEhAgADBAgQICQgUKECQkIAgAQIFChQoWKBAIQGBAgUKFCgkIECAYAECBAsQIAA) is just one row short of being able to fit. I tried using a wall line in the gap but the app wouldn't let me

To keep from making the grid too large on the screen, and to allow your grid resizing to work, perhaps you could just make a very large grid and just resize the view port? Then you could add controls to drag/slide the grid around. That would allow users to create larger maps and just slide the part they need into view

**Comment by AluminumAngel** [comment]
I agree with that solution, and I have been working on exactly that.

It needs to also come with an optimization that reduces the solved grid size do the bounds of the problem space, so I don't overload my server with every solution request.

It will be a bit before I release this feature. My day job is ramping up to a product release currently.

**Comment by AluminumAngel** [comment]
Grid size has been increased.
