### ISSUE TITLE
Frosthaven movement priorities incorrect for multitarget attacks

### ISSUE THREAD

**Issue by rmsgrey** [AluminumAngel/gloom#40]
As discussed here: https://boardgamegeek.com/thread/3047722

In Frosthaven mode, when given the option between attacking primary and secondary targets with disadvantage on the primary, or moving to attack primary and tertiary targets without any disadvantage, the monster attacks two targets (including primary) with disadvantage on one rather than attacking two targets (including primary) without disadvantage.

Expected behaviour is:
A) Maximise number of targets (including focus)
B) Break ties by minimising number of disadvantages attacks (regardless of whether the focus is among them - which is changed from Gloomhaven)
?C) (not officially confirmed, but not directly contradicted and follows the rulebook) Break ties by move required
D) Break ties by player choice (outside scope of this tool)

**Comment by AluminumAngel** [comment]
This is resolved in v2.12.0, just deployed. I'll close the ticket when the source is uploaded.

**Comment by AluminumAngel** [comment]
I take that back. There remains a lingering issue.

**Comment by AluminumAngel** [comment]
Lingering issue is resolved in v2.12.1.

**Comment by AluminumAngel** [comment]
Resolved all issues associated with recent Frosthaven FAQ updates.
