### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by solomojb** [AluminumAngel/gloom#44]
Hey!

I went to use the mover tonight and I am getting a 502 error.

I figured I would pull down the code and try to run it locally.

I ran `npm run-script watch`, but how do I view in the browser, and I assume I have to run the server? (But unsure how to do that as well)

Got any build instructions?

thanks
~s

**Comment by AluminumAngel** [comment]
Sorry about that. My server host decided to turn off linger without telling me. Fixing now.

**Comment by AluminumAngel** [comment]
Fixed.

**Comment by AluminumAngel** [comment]
To answer you question, however:

I include the bundled js (bundle.js), so you don't need to run `npm run watch` unless you make JS changes.

On how to run the server, I'm in an awkward spot to answer that. I have a local pull that switches the server from using Passenger to Gunicorn. (My server host is dropping Passenger support.) So, I need to remember how to run a local server for the version in Github. And even if I think I remember, I cannot test the steps.

- Install Flask. I believe version 0.9.
- In the server directory of the install, run: `python __init__.py`
- You will get various missing package errors. Use pip to install needed package. Rinse and repeat. Eventually the server should run.
- Connect a browser to `http://127.0.0.1:8000/`
