### ISSUE TITLE
miscalculation with traps with "Move 3"

### ISSUE THREAD

**Issue by sandorkazi** [AluminumAngel/gloom#7]
Here is an example setting:

![Screenshot_20201020_203435](https://user-images.githubusercontent.com/5766296/96629732-5027ee80-1314-11eb-9069-a8178112e596.png)

This is clearly a bug as:
- this is a melee monster not jumping or flying but it still plans to hit 4 of the traps instead of the minimum 3
- by going right it could choose the other attack hex as destination without extra movement needed... hence avoiding one more trap... but it does not... it deliberately goes for the trap
- it goes right even though the number of traps are the same each direction... and leftwise would be shorter...
- if I increase or decrease the movement number by just one it goes left

**Comment by AluminumAngel** [comment]
Definitely a bug.  Thanks for the report.  I'll check it out.

**Comment by AluminumAngel** [comment]
https://gloom.aluminumangel.org/AQwEhAREJCdAgAAhBEEDBggdCBIgYPhAEAwQgMIHAgYIECCEIGDAAAHCBwIEChBSECCcIEAA

**Comment by AluminumAngel** [comment]
Fixed in v2.4.9.

When picking a path to its destination, the monster was valuing future traps higher than traps traversed during its move.  Now both traps are of equal value.
